name: Synchronize with remote repository
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout BitBucket repository
        run: git clone --bare https://${{ secrets.GITHUB_ACTOR }}:${{ secrets.BITBUCKET }}@bitbucket.org/Aust1n46/venturechat.git BitBucket
      - name: Fetch Tags
        working-directory: BitBucket
        run: git fetch origin --tags
      - name: Add GitHub remote
        working-directory: BitBucket
        run: git remote add --mirror=fetch github https:/${{ secrets.GITHUB_ACTOR }}:${{ secrets.GITHUB_TOKEN }}@/github.com/regulad/VentureChat.git
      - name: Push Changes
        working-directory: BitBucket
        run: |
          git push github --all
          git push github --tags
